FROM python:3.11.2-slim-bullseye

WORKDIR /app

COPY pyproject.toml constraints.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -c constraints.txt ".[dev]"

COPY test/ test/

