name: Employees Build
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
jobs:
  build:
      name: Build binary
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.13'
              cache: 'pip' # caching pip dependencies
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -c constraints.txt .[dev]
          # - name: Static code analysis
          #   run: pre-commit run --all-files
          - name: Run unit tests
            run: python -m pytest -v test/unit/
          - name: Build
            run: python -m build
          - name: Create Docker image
            run: docker build -t employees .
          - name: Create test Docker image
            run: docker build -t employees-test -f Dockerfile.test .
          - name: Run E2E tests
            working-directory: ./employees
            run: docker compose --profile api-test up --abort-on-container-exit