name: Employees Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
      name: Build binary
      runs-on: ubuntu-latest
      permissions:
        packages: write
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.13'
              cache: 'pip' # caching pip dependencies
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install -c constraints.txt .[dev]
          # - name: Static code analysis
          #   run: pre-commit run --all-files
          # - name: Run unit tests
          #   run: python -m pytest -v test/unit/
          - name: Build
            run: python -m build
          - name: Create Docker image
            run: docker build -t employees .
          - name: Create test Docker image
            run: docker build -t employees-test -f Dockerfile.test .
          # - name: Run E2E tests
          #   working-directory: ./employees
          #   run: docker compose --profile api-test up --abort-on-container-exit
          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Generate Docker image metadata
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/${{ github.repository }}    
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}