name: Employees Build
on:
    push
jobs:
    build:
        name: Build binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                cache: 'pip' # caching pip dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -c constraints.txt .[dev]
            - name: Run unit tests
              run: python -m pytest -v test/unit/
